### ISSUE TITLE
Why performance exact version check in tardy?

### ISSUE THREAD

**Issue by marcoziti** [tardy-org/tardy#23]
Hi,

I am curious the reason to perform exact version check at build.zig of tardy project as below which leads to compilation failure of project zzz:
```
comptime {
    // Compare versions while allowing different pre/patch metadata.
    const zig_version_eq = zig_version.major == builtin.zig_version.major and
        zig_version.minor <= builtin.zig_version.minor and
        zig_version.patch <= builtin.zig_version.patch;
    if (!zig_version_eq) {
        @compileError(std.fmt.comptimePrint(
            "unsupported zig version: expected {}, found {}",
            .{ zig_version, builtin.zig_version },
        ));
    }
}
```

error:
```
/home/jojo/.cache/zig/p/tardy-0.3.0-69wrgi7PAwDFhO7m0aXae6N15s2b28VIOrnRrSHHake6/build.zig:12:9: error: unsupported zig version: expected 0.14.0, found 0.15.0-dev.589+23c817548
        @compileError(std.fmt.comptimePrint(
        ^~~~~~~~~~~~~
referenced by:
    build_zig: /tmp/zig-local-cache/o/f5e696e81d272108b1b46d38fd38ae27/dependencies.zig:23:39
    dependency__anon_99422: /nix/store/hxvvh1dg40gzdl8fnaijik9c8zwkff79-zig-0.15.0-dev.589+23c817548/lib/std/Build.zig:2237:96
    15 reference(s) hidden; use '-freference-trace=17' to see all references
```

After test of different zig version, it seems tarday+zzz work in ```zig v0.14.1' and ```zig v0.15.0-dev.589+23c817548``` and all tests pass.

If in this case, would it make sense to only check minimum version needed?

**Comment by mookums** [comment]
This was a historical change and it's just been there since I've been busy. I'll get around to this eventually but also feel free to make a PR.
